PRAGMA ENCODING     = "UTF-8";
PRAGMA FOREIGN_KEYS = ON;

/* ИНСТРУКТАЖИ, АТТЕСТАЦИЯ, ОБУЧЕНИЕ */
CREATE TABLE IF NOT EXISTS BRIEFINGMAIN (
    BRIEFID   INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    BRIEFNAME TEXT     NOT NULL,
    BEGINDATE DATETIME NOT NULL,
    ENDDATE   DATETIME NOT NULL,
    OBJECT    INTEGER  NOT NULL,
    PERIOD    INTEGER  NOT NULL,
    NUM       INTEGER  NOT NULL DEFAULT 0,
    LASTDATE  DATETIME NOT NULL DEFAULT 0,
    NOTE      TEXT     NOT NULL
);

/* СПИСОК РАБОТНИКОВ */
CREATE TABLE IF NOT EXISTS STAFFMAIN (
    STAFFID    INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME       TEXT     NOT NULL,
    PATRONYMIC TEXT    ,
    FAMILY     TEXT     NOT NULL,
    BORNDATE   DATETIME NOT NULL,
    GENDER     INTEGER  NOT NULL DEFAULT 1,
    FULLNAME   TEXT     NOT NULL
);

/* СПИСОК ДОЛЖНОСТЕЙ */
CREATE TABLE IF NOT EXISTS STAFFPOST (
    POSTID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    POSTNAME TEXT    UNIQUE NOT NULL
);
INSERT OR IGNORE INTO  STAFFPOST (POSTID, POSTNAME) VALUES (0, '<не указана>');

/* СПИСОК ТАБЕЛЬНЫХ НОМЕРОВ */
CREATE TABLE IF NOT EXISTS STAFFTABNUM (
    TABNUMID    INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUM      TEXT     NOT NULL,
    STAFFID     INTEGER  NOT NULL,
    RECRUTDATE  DATETIME NOT NULL,
    DISMISSDATE DATETIME NOT NULL,
    CONSTRAINT FK_STAFFTABNUM_STAFFID FOREIGN KEY (STAFFID) REFERENCES STAFFMAIN(STAFFID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* КОРРЕКТИРОВКИ ПРОИЗВОДСТВЕННОГО КАЛЕНДАРЯ */
CREATE TABLE IF NOT EXISTS CALENDAR (
    DAYDATE DATETIME PRIMARY KEY NOT NULL,
    STATUS  INTEGER  NOT NULL,
    SWAPDAY INTEGER  NOT NULL DEFAULT 0
);

/* ТАБЛИЦА ИСПОЛЬЗУЕМЫХ ПО УМОЛЧАНИЮ ЦВЕТОВ */
CREATE TABLE IF NOT EXISTS COLORS (
    COLORNAME  TEXT    PRIMARY KEY NOT NULL,
    COLORVALUE INTEGER NOT NULL
);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('CalendarHoliday', 9948159);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('CalendarOffday', 13427660);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('CalendarBefore', 16763594);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('CalendarWeekday', 16777215);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('ShiftScheduleWork', 16777215);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('ShiftScheduleNotWork', 13427660);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('ShiftScheduleCorrect', 11796479);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('PersonalScheduleNotWork', 13427660);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('PersonalScheduleCorrect', 11796479);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('TimetableHoliday', 9948159);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('TimetableBefore', 16763594);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('TimetableManual', 13427660);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('SizLifeOff', 13816575);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('SizLifeEnd', 11796479);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('PlaneVacationAddColor', 14079702);
INSERT OR IGNORE INTO  COLORS (COLORNAME, COLORVALUE) VALUES ('PlaneVacationMainColor', 13427660);

/* СПИСОК МЕТОК (КОДОВ) ТАБЕЛЯ */
CREATE TABLE IF NOT EXISTS TIMETABLEMARK (
    DIGMARK  INTEGER PRIMARY KEY NOT NULL,
    STRMARK  TEXT    NOT NULL,
    NOTE     TEXT    NOT NULL,
    TYPEMARK INTEGER NOT NULL
);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (0, '?', '<не указано>', 0);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (-1, 'В', 'Отпуск в праздничный день', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (1, 'Я', 'Продолжительность работы в дневное время', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (2, 'Н', 'Продолжительность работы в ночное время', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (3, 'РВ', 'Продолжительность работы в выходные и нерабочие праздничные дни', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (4, 'С', 'Продолжительность сверхурочной работы', 3);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (5, 'ВМ', 'Продолжительность работы вахтовым методом', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (6, 'К', 'Служебная командировка', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (7, 'ПК', 'Повышение квалификации с отрывом от работы', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (8, 'ПМ', 'Повышение квалификации с отрывом от работы в другой местности', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (9, 'ОТ', 'Ежегодный основной оплачиваемый отпуск', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (10, 'ОД', 'Ежегодный дополнительный оплачиваемый отпуск', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (11, 'У', 'Дополнительный отпуск в связи с обучением с сохранением среднего заработка работникам, совмещающим работу с обучением', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (12, 'УВ', 'Сокращенная продолжительность рабочего времени для обучающихся без отрыва от производства с частичным сохранением заработной платы', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (13, 'УД', 'Дополнительный отпуск в связи с обучением без сохранения заработной платы', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (14, 'Р', 'Отпуск по беременности и родам (отпуск в связи с усыновлением новорожденного ребенка)', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (15, 'ОЖ', 'Отпуск по уходу за ребенком до достижения им возраста трех лет', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (16, 'ДО', 'Отпуск без сохранения заработной платы, предоставленный работнику по разрешению работодателя', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (17, 'ОЗ', 'Отпуск без сохранения заработной платы в случаях, предусмотренных законодательством', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (18, 'ДБ', 'Ежегодный дополнительный отпуск без сохранения заработной платы', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (19, 'Б', 'Временная нетрудоспособность (кроме случаев, предусмотренных кодом "20") с назначением пособия согласно законодательству', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (20, 'Т', 'Временная нетрудоспособность без назначения пособия в случаях, предусмотренных законодательством', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (21, 'ЛЧ', 'Сокращенная продолжительность рабочего времени против нормальной продолжительности рабочего дня в случаях, предусмотренных законодательством', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (22, 'ПВ', 'Время вынужденного прогула в случае признания увольнения, перевода на другую работу или отстранения от работы незаконными с восстановлением на прежней работе', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (23, 'Г', 'Невыходы на время исполнения государственных или общественных обязанностей согласно законодательству', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (24, 'ПР', 'Прогулы (отсутствие на рабочем месте без уважительных причин в течение времени, установленного законодательством)', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (25, 'НС', 'Продолжительность работы в режиме неполного рабочего времени по инициативе работодателя в случаях, предусмотренных законодательством', 1);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (26, 'В', 'Выходные дни (еженедельный отпуск) и нерабочие праздничные дни', 4);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (27, 'ОВ', 'Дополнительные выходные дни (оплачиваемые)', 4);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (28, 'НВ', 'Дополнительные выходные дни (без сохранения заработной платы)', 4);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (29, 'ЗБ', 'Забастовка (при условиях и в порядке, предусмотренных законом)', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (30, 'НН', 'Неявки по невыясненным причинам (до выяснения обстоятельств)', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (31, 'РП', 'Время простоя по вине работодателя', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (32, 'НП', 'Время простоя по причинам, не зависящим от работодателя и работника', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (33, 'ВП', 'Время простоя по вине работника', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (34, 'НО', 'Отстранение от работы (недопущение к работе) с оплатой (пособием) в соответствии с законодательством', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (35, 'НБ', 'Отстранение от работы (недопущение к работе) по причинам, предусмотренным законодательством, без начисления заработной платы', 2);
INSERT OR IGNORE INTO  TIMETABLEMARK (DIGMARK, STRMARK, NOTE, TYPEMARK) VALUES (36, 'НЗ', 'Время приостановки работы в случае задержки выплаты заработной платы', 2);

/* СПИСОК ГРАФИКОВ СМЕННОСТИ */
CREATE TABLE IF NOT EXISTS SCHEDULEMAIN (
    SCHEDULEID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    SCHEDULENAME TEXT    UNIQUE NOT NULL,
    WEEKHOURS    INTEGER NOT NULL DEFAULT 40,
    CYCLECOUNT   INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO  SCHEDULEMAIN (SCHEDULEID, SCHEDULENAME, WEEKHOURS, CYCLECOUNT) VALUES (0, '<не указан>', 0, 0);
INSERT OR IGNORE INTO  SCHEDULEMAIN (SCHEDULEID, SCHEDULENAME, WEEKHOURS, CYCLECOUNT) VALUES (-1, 'КОРРЕКТИРОВКА ТАБЕЛЯ', 0, 0);

/* ЦИКЛЫ ГРАФИКОВ СМЕННОСТИ */
CREATE TABLE IF NOT EXISTS SCHEDULECYCLE (
    CYCLEID    INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    SCHEDULEID INTEGER  NOT NULL,
    DAYDATE    DATETIME NOT NULL,
    HOURSTOTAL INTEGER  NOT NULL,
    HOURSNIGHT INTEGER  NOT NULL,
    DIGMARK    INTEGER  NOT NULL DEFAULT 0,
    SHIFTNUM   INTEGER  NOT NULL DEFAULT 0,
    CONSTRAINT FK_SCHEDULECYCLE_SCHEDULEID FOREIGN KEY (SCHEDULEID) REFERENCES SCHEDULEMAIN(SCHEDULEID)  ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SCHEDULECYCLE_DIGMARK    FOREIGN KEY (DIGMARK)    REFERENCES TIMETABLEMARK(DIGMARK)    ON UPDATE CASCADE ON DELETE SET DEFAULT
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SCHEDULECYCLE_SCHEDULEIDDATE ON SCHEDULECYCLE(SCHEDULEID, DAYDATE);

/* КОРРЕКТИРОВКИ ГРАФИКОВ СМЕННОСТИ */
CREATE TABLE IF NOT EXISTS SCHEDULECORRECT (
    CORRECTID  INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    SCHEDULEID INTEGER  NOT NULL,
    DAYDATE    DATETIME NOT NULL,
    HOURSTOTAL INTEGER  NOT NULL,
    HOURSNIGHT INTEGER  NOT NULL,
    DIGMARK    INTEGER  NOT NULL DEFAULT 0,
    SHIFTNUM   INTEGER  NOT NULL DEFAULT 0,
    CONSTRAINT FK_SCHEDULECORRECT_SCHEDULEID FOREIGN KEY (SCHEDULEID) REFERENCES SCHEDULEMAIN(SCHEDULEID)  ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SCHEDULECORRECT_DIGMARK    FOREIGN KEY (DIGMARK)    REFERENCES TIMETABLEMARK(DIGMARK)    ON UPDATE CASCADE ON DELETE SET DEFAULT
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SCHEDULECORRECT_SCHEDULEIDDATE ON SCHEDULECORRECT(SCHEDULEID, DAYDATE);

/* ПОЛЬЗОВАТЕЛЬСКИЕ ПАРАМЕТРЫ */
CREATE TABLE IF NOT EXISTS SETTINGS (
    NAME  TEXT    PRIMARY KEY NOT NULL,
    VALUE INTEGER NOT NULL
);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.LISTTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.ORDERTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.NUMBER', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.STAFFNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.BORNDATE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.GENDER', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.TABNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.RECRUTDATE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.DISMISSDATE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.RANK', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.POSTNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('STAFFORM.NAMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTCALENDARFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTCALENDARFORM.NEEDCORRECTIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTCALENDARFORM.FIRSTSHIFTDAYCOLORONLY', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTMONTHFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.NEEDCORRECTIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.NEEDNIGHTHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.NEEDNOTWORKMARKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.NEEDCOLORS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.RESUMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULESHIFTFORM.COLORTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.NEEDCORRECTIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.NEEDNIGHTHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.NEEDNOTWORKMARKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.NEEDVACATIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.NEEDCOLORS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.RESUMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALFORM.COLORTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NEEDNIGHTHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NEEDCORRECTIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NEEDNOTWORKMARKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NEEDVACATIONS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.RESUMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.PERIODTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.ORDERNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.POSTNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.TABNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.DAYSCOUNT', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.SUMHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NORMHOURS', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.DELTAHOURS', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.SIGNATURETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.REPEATTITLE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.PAGENUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEFORM.NEEDCOLORS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEFORM.RESUMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.TIMETABLETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.VIEWTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.MONTHTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.NEEDNIGHTHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.NEEDNOTWORKMARKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.PERIODTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.COUNTTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.ORDERNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.POSTNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.TABNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.DAYSCOUNT', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.SUMHOURS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.NORMHOURS', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.DELTAHOURS', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.NIGHTHOURS', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.REPEATTITLE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.PAGENUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.LINETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.ORDERTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.RECRUTTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.NUMBER', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.STAFFNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.TABNUM', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.POSTNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.RECRUTDATE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.FIRSTPART', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.SECONDPART', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANFORM.NAMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONPLANNINGFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('CALENDARFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('VACATIONSCHEDULEFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.LISTTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.ORDERTYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.NUMBER', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.STAFFNAME', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.CLOTHES', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.SHOES', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.HEADDRESS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.MITTENS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.GLOVES', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.GASMASK', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.RESPIRATOR', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSIZEFORM.NAMETYPE', 0);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDFRONTFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDBACKFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDSTATUSFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDSTATUSFORM.WARNDAYSCOUNT', 50);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDFORM.LISTTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZCARDFORM.WRITEOFFTYPE', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZDOCMB7FORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZSTAFFHISTORYFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SIZREQUESTFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('BRIEFINGFORM.ZOOM', 100);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('SCHEDULEPERSONALMONTHFORM.NEEDRANKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('TIMETABLEMONTHFORM.NEEDRANKS', 1);
INSERT OR IGNORE INTO  SETTINGS (NAME, VALUE) VALUES ('BRIEFINGLOGFORM.LISTTYPE', 1);

/* ТАБЛИЦА ЦВЕТОВ CМЕН ГРАФИКА-КАЛЕНДАРЯ */
CREATE TABLE IF NOT EXISTS SHIFTCOLORS (
    COLORINDEX INTEGER PRIMARY KEY NOT NULL,
    COLORVALUE INTEGER NOT NULL
);

/* СПИСОК ТИПОВЫХ НОРМ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZNORM (
    NORMID    INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    NORMNAME  TEXT     UNIQUE NOT NULL,
    BEGINDATE DATETIME NOT NULL,
    ENDDATE   DATETIME NOT NULL,
    NOTE      TEXT    
);

/* ПУНКТЫ ТИПОВОЙ НОРМЫ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZNORMITEM (
    ITEMID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ORDERNUM INTEGER NOT NULL,
    NORMID   INTEGER NOT NULL,
    CONSTRAINT FK_SIZNORMITEM_NORMID FOREIGN KEY (NORMID) REFERENCES SIZNORM(NORMID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* СООТВЕТСТВИЕ ПУНКТА ТИПОВОЙ НОРМЫ ВЫДАЧИ СИЗ ДОЛЖНОСТИ РАБОТНИКА */
CREATE TABLE IF NOT EXISTS SIZNORMITEMPOST (
    ITEMPOSTID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ITEMID     INTEGER NOT NULL,
    POSTID     INTEGER NOT NULL,
    CONSTRAINT FK_SIZNORMITEMPOST_ITEMID FOREIGN KEY (ITEMID) REFERENCES SIZNORMITEM(ITEMID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZNORMITEMPOST_POSTID FOREIGN KEY (POSTID) REFERENCES STAFFPOST(POSTID)   ON UPDATE CASCADE ON DELETE CASCADE
);

/* СПИСОК ДОКУМЕНТОВ ВЫДАЧИ/СПИСАНИЯ/ВОЗВРАТА СИЗ */
CREATE TABLE IF NOT EXISTS SIZDOC (
    DOCID   INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    DOCNAME TEXT     NOT NULL,
    DOCDATE DATETIME NOT NULL,
    DOCNUM  TEXT     NOT NULL,
    DOCTYPE INTEGER  NOT NULL DEFAULT 0,
    DOCFORM INTEGER  NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SIZDOC_DOCNAMENUMDATE ON SIZDOC(DOCNAME, DOCDATE, DOCNUM);

/* ЕДИНИЦЫ ИЗМЕРЕНИЯ СИЗ */
CREATE TABLE IF NOT EXISTS SIZUNIT (
    UNITID          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UNITNAME        TEXT    UNIQUE NOT NULL,
    UNITDIGITALCODE INTEGER NOT NULL,
    UNITSTRINGCODE  TEXT    UNIQUE NOT NULL
);
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (0, '<не указана>', 0, ' ');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (1, 'Штука', 796, 'шт');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (2, 'Пара', 715, 'пар');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (3, 'Комплект', 839, 'компл');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (4, 'Грамм', 163, 'г');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (5, 'Килограмм', 166, 'кг');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (6, 'Кубический дециметр', 112, 'куб. дм');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (7, 'Кубический сантиметр', 111, 'куб. см');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (8, 'Литр', 112, 'л');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (9, 'Миллиграмм', 161, 'мг');
INSERT OR IGNORE INTO  SIZUNIT (UNITID, UNITNAME, UNITDIGITALCODE, UNITSTRINGCODE) VALUES (10, 'Миллилитр', 111, 'мл');

/* ЛИЧНЫЕ КАРТОЧКИ УЧЕТА ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZCARDPERSONAL (
    CARDID     INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    CARDNUM    TEXT    NOT NULL,
    TABNUMID   INTEGER NOT NULL,
    ITEMPOSTID INTEGER NOT NULL,
    CONSTRAINT FK_SIZCARDPERSONAL_TABNUMID   FOREIGN KEY (TABNUMID)   REFERENCES STAFFTABNUM(TABNUMID)       ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZCARDPERSONAL_ITEMPOSTID FOREIGN KEY (ITEMPOSTID) REFERENCES SIZNORMITEMPOST(ITEMPOSTID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* СПИСОК ДОПОЛНИТЕЛЬНЫХ УСЛОВИЙ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZREASON (
    REASONID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    REASONNAME TEXT    UNIQUE NOT NULL
);
INSERT OR IGNORE INTO  SIZREASON (REASONID, REASONNAME) VALUES (0, '<не указано>');

/* ПОДПУНКТЫ (СТРОКИ) ПУНКТА ТИПОВОЙ НОРМЫ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZNORMSUBITEM (
    SUBITEMID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ITEMID    INTEGER NOT NULL,
    REASONID  INTEGER NOT NULL DEFAULT 0,
    ORDERNUM  INTEGER NOT NULL,
    CONSTRAINT FK_SIZNORMSUBITEM_ITEMID   FOREIGN KEY (ITEMID)   REFERENCES SIZNORMITEM(ITEMID)   ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZNORMSUBITEM_REASONID FOREIGN KEY (REASONID) REFERENCES SIZREASON(REASONID)   ON UPDATE CASCADE ON DELETE SET DEFAULT
);

/* НАИМЕНОВАНИЯ СИЗ */
CREATE TABLE IF NOT EXISTS SIZNAME (
    NAMEID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    SIZNAME  TEXT    UNIQUE NOT NULL,
    SIZTYPE  INTEGER NOT NULL,
    UNITID   INTEGER NOT NULL DEFAULT 0,
    SIZETYPE INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT FK_SIZNAME_UNITID FOREIGN KEY (UNITID) REFERENCES SIZUNIT(UNITID) ON UPDATE CASCADE ON DELETE SET DEFAULT
);

/* ПОДСТРОКА ПОДПУНКТА (СТРОКИ) ПУНКТА ТИПОВОЙ НОРМЫ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZNORMSUBITEMINFO (
    INFOID     INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    SUBITEMID  INTEGER NOT NULL,
    NAMEID     INTEGER NOT NULL,
    NUM        INTEGER NOT NULL DEFAULT 1,
    LIFE       INTEGER NOT NULL DEFAULT 0,
    ORDERNUM   INTEGER NOT NULL,
    CLAUSENAME TEXT    NOT NULL,
    CONSTRAINT FK_SIZNORMSUBITEMINFO_SUBITEMID FOREIGN KEY (SUBITEMID) REFERENCES SIZNORMSUBITEM(SUBITEMID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZNORMSUBITEMINFO_NAMEID    FOREIGN KEY (NAMEID)    REFERENCES SIZNAME(NAMEID)           ON UPDATE CASCADE ON DELETE CASCADE
);

/* ЖУРНАЛ ВЫДАЧИ СИЗ */
CREATE TABLE IF NOT EXISTS SIZCARDPERSONALLOG (
    LOGID           INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    CARDID          INTEGER  NOT NULL,
    RECEIVINGDATE   DATETIME NOT NULL,
    DOCID           INTEGER  NOT NULL,
    RECEIVINGINFOID INTEGER  NOT NULL,
    NOWINFOID       INTEGER  NOT NULL,
    CONSTRAINT FK_SIZCARDPERSONALLOG_CARDID          FOREIGN KEY (CARDID)          REFERENCES SIZCARDPERSONAL(CARDID)    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZCARDPERSONALLOG_DOCID           FOREIGN KEY (DOCID)           REFERENCES SIZDOC(DOCID)              ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZCARDPERSONALLOG_RECEIVINGINFOID FOREIGN KEY (RECEIVINGINFOID) REFERENCES SIZNORMSUBITEMINFO(INFOID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZCARDPERSONALLOG_NOWINFOID       FOREIGN KEY (NOWINFOID)       REFERENCES SIZNORMSUBITEMINFO(INFOID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* СПИСОК ПОСТУПЛЕНИЯ СИЗ НА СКЛАД */
CREATE TABLE IF NOT EXISTS SIZSTOREENTRY (
    ENTRYID    INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOMNUM     TEXT    NOT NULL,
    NAMEID     INTEGER NOT NULL,
    SIZEID     INTEGER NOT NULL DEFAULT 0,
    HEIGHTID   INTEGER NOT NULL DEFAULT 0,
    ENTRYCOUNT INTEGER NOT NULL DEFAULT 1,
    DOCID      INTEGER NOT NULL,
    ENTRYNOTE  TEXT   ,
    CONSTRAINT FK_SIZSTOREENTRY_NAMEID FOREIGN KEY (NAMEID) REFERENCES SIZNAME(NAMEID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZSTOREENTRY_DOCID  FOREIGN KEY (DOCID)  REFERENCES SIZDOC(DOCID)   ON UPDATE CASCADE ON DELETE CASCADE
);

/* РАЗМЕРЫ СИЗ В ЛИЧНЫХ КАРТОЧКАХ РАБОТНИКОВ */
CREATE TABLE IF NOT EXISTS SIZSTAFFSIZE (
    STAFFID    INTEGER UNIQUE NOT NULL,
    CLOTHES    INTEGER NOT NULL DEFAULT 0,
    HEIGHT     INTEGER NOT NULL DEFAULT 0,
    SHOES      INTEGER NOT NULL DEFAULT 0,
    HEAD       INTEGER NOT NULL DEFAULT 0,
    HAND       INTEGER NOT NULL DEFAULT 0,
    GASMASK    INTEGER NOT NULL DEFAULT 0,
    RESPIRATOR INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT FK_SIZSTAFFSIZE_STAFFID FOREIGN KEY (STAFFID) REFERENCES STAFFMAIN(STAFFID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* ОСОБЫЕ РАЗМЕРЫ СИЗ РАБОТНИКОВ В ПОДСТРОКАХ ПУНКТОВ ТИПОВЫХ НОРМ */
CREATE TABLE IF NOT EXISTS SIZSTAFFSPECSIZE (
    TABNUMID INTEGER NOT NULL,
    INFOID   INTEGER NOT NULL,
    SIZEID   INTEGER NOT NULL DEFAULT 0,
    HEIGHTID INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT FK_SIZSTAFFSPECSIZE_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID)        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZSTAFFSPECSIZE_INFOID   FOREIGN KEY (INFOID)   REFERENCES SIZNORMSUBITEMINFO(INFOID)   ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_SIZSTAFFSPECSIZE_TABNUMIDINFOID ON SIZSTAFFSPECSIZE(TABNUMID, INFOID);

/* СПИСОК СИЗ НА СКЛАДЕ (каждой единице СИЗ из списка поступления соответствует одна запись) */
CREATE TABLE IF NOT EXISTS SIZSTORELOG (
    STOREID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ENTRYID INTEGER NOT NULL,
    ISBUSY  INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT FK_SIZSTORELOG_ENTRYID FOREIGN KEY (ENTRYID) REFERENCES SIZSTOREENTRY(ENTRYID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* ИНФОРМАЦИЯ О ВОЗВРАТЕ СИЗ СОТРУДНИКАМИ */
CREATE TABLE IF NOT EXISTS SIZSTAFFRETURN (
    RETURNID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DOCID         INTEGER NOT NULL,
    STOREID       INTEGER NOT NULL,
    RETURNSTOREID INTEGER NOT NULL,
    NOTE          TEXT   ,
    CONSTRAINT FK_SIZSTAFFRETURN_DOCID         FOREIGN KEY (DOCID)         REFERENCES SIZDOC(DOCID)        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZSTAFFRETURN_STOREID       FOREIGN KEY (STOREID)       REFERENCES SIZSTORELOG(STOREID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZSTAFFRETURN_RETURNSTOREID FOREIGN KEY (RETURNSTOREID) REFERENCES SIZSTORELOG(STOREID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* ИНФОРМАЦИЯ О СПИСАНИИ СО СКЛАДА */
CREATE TABLE IF NOT EXISTS SIZSTOREWRITEOFF (
    WRITEOFFID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DOCID      INTEGER NOT NULL,
    STOREID    INTEGER NOT NULL,
    NOTE       TEXT   ,
    CONSTRAINT FK_SIZSTOREWRITEOFF_DOCID   FOREIGN KEY (DOCID)   REFERENCES SIZDOC(DOCID)        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZSTOREWRITEOFF_STOREID FOREIGN KEY (STOREID) REFERENCES SIZSTORELOG(STOREID) ON UPDATE CASCADE ON DELETE CASCADE
);

/* ИНФОРМАЦИЯ ПО ЗАПИСИ ЖУРНАЛА ВЫДАЧИ СИЗ (СПИСОК ВЫДАННОГО) */
CREATE TABLE IF NOT EXISTS SIZCARDPERSONALLOGINFO (
    LOGINFOID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    LOGID     INTEGER NOT NULL,
    STOREID   INTEGER NOT NULL,
    CONSTRAINT FK_SIZCARDPERSONALLOGINFO_LOGID   FOREIGN KEY (LOGID)   REFERENCES SIZCARDPERSONALLOG(LOGID)   ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SIZCARDPERSONALLOGINFO_STOREID FOREIGN KEY (STOREID) REFERENCES SIZSTORELOG(STOREID)        ON UPDATE CASCADE ON DELETE CASCADE
);

/* ТАБЕЛЬНЫЕ НОМЕРА, ДЛЯ КОТОРЫХ ПРОВОДИТСЯ ИНСТРУКТАЖ */
CREATE TABLE IF NOT EXISTS BRIEFINGTABNUM (
    ID       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    BRIEFID  INTEGER NOT NULL,
    TABNUMID INTEGER NOT NULL,
    CONSTRAINT FK_BRIEFINGTABNUM_BRIEFID  FOREIGN KEY (BRIEFID)  REFERENCES BRIEFINGMAIN(BRIEFID)  ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_BRIEFINGTABNUM_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID)  ON UPDATE CASCADE ON DELETE CASCADE
);

/* ДОЛЖНОСТИ, ДЛЯ КОТОРЫХ ПРОВОДИТСЯ ИНСТРУКТАЖ */
CREATE TABLE IF NOT EXISTS BRIEFINGPOST (
    ID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    BRIEFID INTEGER NOT NULL,
    POSTID  INTEGER NOT NULL,
    CONSTRAINT FK_BRIEFINGPOST_BRIEFID FOREIGN KEY (BRIEFID) REFERENCES BRIEFINGMAIN(BRIEFID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_BRIEFINGPOST_POSTID  FOREIGN KEY (POSTID)  REFERENCES STAFFPOST(POSTID)     ON UPDATE CASCADE ON DELETE CASCADE
);

/* ДАННЫЕ О ПЕРЕВОДАХ */
CREATE TABLE IF NOT EXISTS STAFFPOSTLOG (
    ID        INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUMID  INTEGER  NOT NULL,
    POSTID    INTEGER  NOT NULL DEFAULT 0,
    FIRSTDATE DATETIME NOT NULL,
    LASTDATE  DATETIME NOT NULL,
    POSTTEMP  INTEGER  NOT NULL DEFAULT 0,
    RANK      TEXT    ,
    CONSTRAINT FK_STAFFPOSTLOG_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_STAFFPOSTLOG_POSTID   FOREIGN KEY (POSTID)   REFERENCES STAFFPOST(POSTID)     ON UPDATE CASCADE ON DELETE SET DEFAULT
);

/* ГРАФИКИ РАБОТНИКОВ */
CREATE TABLE IF NOT EXISTS STAFFSCHEDULE (
    ID         INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUMID   INTEGER  NOT NULL,
    SCHEDULEID INTEGER  NOT NULL DEFAULT 0,
    BEGINDATE  DATETIME NOT NULL,
    ENDDATE    DATETIME NOT NULL,
    CONSTRAINT FK_STAFFSCHEDULE_TABNUMID   FOREIGN KEY (TABNUMID)   REFERENCES STAFFTABNUM(TABNUMID)    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_STAFFSCHEDULE_SCHEDULEID FOREIGN KEY (SCHEDULEID) REFERENCES SCHEDULEMAIN(SCHEDULEID) ON UPDATE CASCADE ON DELETE SET DEFAULT
);

/* ЖУРНАЛ ПРОВЕДЕНИЯ ИНСТРУКТАЖЕЙ */
CREATE TABLE IF NOT EXISTS BRIEFINGLOG (
    LOGID     INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    BRIEFID   INTEGER  NOT NULL,
    TABNUMID  INTEGER  NOT NULL,
    BRIEFDATE DATETIME NOT NULL,
    NEXTDATE  DATETIME NOT NULL DEFAULT 0,
    NOTE      TEXT     NOT NULL,
    CONSTRAINT FK_BRIEFINGLOG_BRIEFID  FOREIGN KEY (BRIEFID)  REFERENCES BRIEFINGMAIN(BRIEFID)  ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_BRIEFINGLOG_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID)  ON UPDATE CASCADE ON DELETE CASCADE
);

/* ОТПУСКА */
CREATE TABLE IF NOT EXISTS STAFFVACATION (
    ID            INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUMID      INTEGER  NOT NULL,
    YEARNUM       INTEGER  NOT NULL,
    PLAN1DATE     DATETIME NOT NULL,
    PLAN1COUNT    INTEGER  NOT NULL DEFAULT 28,
    PLAN1COUNTADD INTEGER  NOT NULL DEFAULT 0,
    PLAN2DATE     DATETIME,
    PLAN2COUNT    INTEGER ,
    PLAN2COUNTADD INTEGER ,
    FACT1DATE     DATETIME,
    FACT1COUNT    INTEGER ,
    FACT1COUNTADD INTEGER ,
    FACT2DATE     DATETIME,
    FACT2COUNT    INTEGER ,
    FACT2COUNTADD INTEGER ,
    CONSTRAINT FK_STAFFVACATION_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_STAFFVACATION_TABNUMIDYEARNUM ON STAFFVACATION(TABNUMID, YEARNUM);

/* ТЕКСТОВЫЕ ПАРАМЕТРЫ */
CREATE TABLE IF NOT EXISTS TEXTPARAMS (
    NAME  TEXT PRIMARY KEY NOT NULL,
    VALUE TEXT
);
INSERT OR IGNORE INTO  TEXTPARAMS (NAME) VALUES ('COMPANY');
INSERT OR IGNORE INTO  TEXTPARAMS (NAME) VALUES ('DEPARTMENT');

/* ТАБЕЛЬ */
CREATE TABLE IF NOT EXISTS TIMETABLELOG (
    TIMETABLEID INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUMID    INTEGER  NOT NULL,
    DAYDATE     DATETIME NOT NULL,
    TOTALHOURS  INTEGER  NOT NULL DEFAULT 0,
    NIGHTHOURS  INTEGER  NOT NULL DEFAULT 0,
    OVERHOURS   INTEGER  NOT NULL DEFAULT 0,
    SKIPHOURS   INTEGER  NOT NULL DEFAULT 0,
    DIGMARK     INTEGER  NOT NULL DEFAULT 0,
    SKIPMARK    INTEGER  NOT NULL DEFAULT 0,
    SCHEDHOURS  INTEGER  NOT NULL DEFAULT 0,
    SCHEDID     INTEGER  NOT NULL DEFAULT 0,
    SHIFTNUM    INTEGER  NOT NULL DEFAULT 0,
    CONSTRAINT FK_TIMETABLELOG_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID)     ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_TIMETABLELOG_DIGMARK  FOREIGN KEY (DIGMARK)  REFERENCES TIMETABLEMARK(DIGMARK)    ON UPDATE CASCADE ON DELETE SET DEFAULT,
    CONSTRAINT FK_TIMETABLELOG_SKIPMARK FOREIGN KEY (SKIPMARK) REFERENCES TIMETABLEMARK(DIGMARK)    ON UPDATE CASCADE ON DELETE SET DEFAULT,
    CONSTRAINT FK_TIMETABLELOG_SCHEDID  FOREIGN KEY (SCHEDID)  REFERENCES SCHEDULEMAIN(SCHEDULEID)  ON UPDATE CASCADE ON DELETE SET DEFAULT
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_TIMETABLELOG_TABNUMDATE ON TIMETABLELOG(TABNUMID, DAYDATE);

/* КОРРЕКТИРОВКИ ПЕРСОНАЛЬНЫХ ГРАФИКОВ */
CREATE TABLE IF NOT EXISTS PERSONALCORRECT (
    CORRECTID  INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    TABNUMID   INTEGER  NOT NULL,
    DAYDATE    DATETIME NOT NULL,
    HOURSTOTAL INTEGER  NOT NULL,
    HOURSNIGHT INTEGER  NOT NULL,
    DIGMARK    INTEGER  NOT NULL DEFAULT 0,
    SHIFTNUM   INTEGER  NOT NULL DEFAULT 0,
    CONSTRAINT FK_PERSONALCORRECT_TABNUMID FOREIGN KEY (TABNUMID) REFERENCES STAFFTABNUM(TABNUMID)   ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_PERSONALCORRECT_DIGMARK  FOREIGN KEY (DIGMARK)  REFERENCES TIMETABLEMARK(DIGMARK)  ON UPDATE CASCADE ON DELETE SET DEFAULT
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_PERSONALCORRECT_TABNUMIDDATE ON PERSONALCORRECT(TABNUMID, DAYDATE);
